@startuml
class Member {
    - id: Long
    - name: String
    - city: String
    - street: String
    - zipcode: String
}

class Order {
    - id: Long
    - memberId: Date
    - status: OrderStatus
}

class OrderItem {
    - id: Long
    - orderId: Long
    - itemId: Long
    - orderPrice: int
    - count: int
}

class Item {
    - id: Long
    - name: String
    - price: int
    - stockQuantity: int
}

Member "1" -- "*" Order
Order "1" - "*" OrderItem
OrderItem "*" -> "1" Item

@enduml
