@startuml
skinparam rectangle {
    roundCorner<<Concept>> 25
}

rectangle " 연관관계 도메인 " <<Concept>> {

    rectangle "회원"
    rectangle "주문"
    rectangle "주문상품"
    rectangle "상품"
    rectangle "카테고리"
    rectangle "배송"

    회원 "1" - "*" 주문
    주문 "1" -- "*" 주문상품
    주문 "1" - "1" 배송
    주문상품 "*" -- "1" 상품
    카테고리 "*" - "*" 상품

}

@enduml